name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
      PROJECT_NAME: rust-covfix
      RUST_BACKTRACE: 1
      TRAVIS_OS_NAME: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Before deploy
        run: bash .ci/before_deploy.sh
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: deploy
